### ISSUE TITLE
Data storage

### ISSUE THREAD

**Issue by keggsmurph21** [SwatPhonLab/UltraTrace#107]
We want to store some data about each project.  This issue should just be for organizing / brainstorming how we want that data to be stored.  My current idea is to, for each `Project` that we open (i.e., pass as a `path` on the command line or open in the `filedialog`):
 - store "metadata" (this was called `metadata.json` in version 1.0
 - store PNG images converted from raw DICOM

One obvious solution to managing this data would be to create a directory structure in the root of the `path`, like
```
/path/.ultratrace/
    |- project.pkl # pickled Project object
    |- frame-data/
        |- ...
        |- <uuid>/ # refers to a specific file (saved in project.pkl)
        |   |- ...
        |   |- <frame>.png
        |   |- ...
        |- ...
```

The only major problem I can see here is the possibility that we won't have write-access to `path`.  With that in mind, maybe it would be better to create a folder in the user's home directory, and then have something like
```
$HOME/.ultratrace/
    |- projects.pkl # store metadata about each Project
    |- projects/
        |- ...
        |- <uuid>/ # refers to a specific project (saved in projects.pkl)
        |   |- project.pkl # pickled Project object
        |   |- frame-data/
        |       |- ...
        |       |- <uuid>/ # refers to a specific file (saved in project.pkl)
        |       |   |- ...
        |       |   |- <frame>.png
        |       |   |- ...
        |       |- ...
        |- ...
```

**Comment by keggsmurph21** [comment]
So, assuming the second case, we'll want `projects.pkl` to have this sort of structure:
```python
 - version: str
   # e.g. "2.0.0"
 - projects: Set[int]
   # where the values in the set are the `__hash__`s of each project `path`
```
Then, we would have some sort of API like
```python
class ProjectManager:
    def get_project_path(self, data_path: str) -> Optional[str]:
        project_hash = hash(data_path)
        if project_hash in self.projects:
            return os.path.join(self.root, "projects", str(project_hash))
        return None
```

**Comment by mr-martian** [comment]
Also note that we currently have 4 methods of getting image data from 2 file types and only 1 of those needs to write files to disk.

**Comment by keggsmurph21** [comment]
Yep, hopefully this will abstract away those details.  By the way, @mr-martian do you have any `.ult` files I could test against?

**Comment by mr-martian** [comment]
Check with @jonorthwash, currently they're on Swat github.

**Comment by jonorthwash** [comment]
I have a couple thoughts here:
- We definitely want traces stored somewhere easy for the user to find, and ideally stored with other project data.
- I'm happy with write access to project directory being a requirement.  A user can always symlink in files from a directory they can't write to into one they can.
- I'd like file names not to be hashes that have to be checked elsewhere.  This is actually a major rule of data archiving - the more transparent the filename, the better.
- Why pickle and not something more widely supported, like json?  Users will want to write R scripts to process traces and the like.

**Comment by kmurphy4** [comment]
Thanks for the reply Jonathan. Regarding your points,

 1) Agreed.  Also, storing the trace data directly with the files obviates the need to explicitly handle the case where users move the directory -- this should just work out of the box.
 2) Ok, if you think that's a reasonable assumption, let's go with that. It's definitely the simpler implementation.
 3) My only concern here is that the hashes are computed based on the full path, so `/path/to/XYZ.dat` and `/path/to/extra-dir/XYZ.dat` would have different hashes. Now that I think about it, maybe we would want those both to map to `XYX`, since the recursive scanner coalesces based on filename anyway.
 4) I agree that supporting some sort of exporting functionality is critical. The reason I'm thinking of using pickle to (en|de) code is that it's completely trivial to (de)serialize complicated data structures. Reading and writing json incurs a nontrivial amount of compute time, especially if we were to follow the current practice of writing everything to disk every time we added a crosshairs. Instead, we should support a simple "export" button _and_ script to create a human readable json object.

**Comment by mr-martian** [comment]
Regarding 4, how much extra time might JSON incur? @BartholomaeusAstrum have you ever noticed any such slowdown?

And would pickle make it difficult to read old files if we ever modify anything in the data structure?

What if we separated the metadata from the traces and had the trace data in some relatively compressed and easy to read/write format?

**Comment by kmurphy4** [comment]
Well I have not benchmarked it, so I can't say for sure, but iterating over each `(file,trace,crosshairs)` could take a long time for projects with a large number of those tuples. On the other hand, `pickle.load()` is more similar to `mmap`ing the relevant data in one go.

Further, development time is much quicker with `pickle` since we don't have to make those serialization decisions yet. Once we feel things are relatively stable, it may be worth revisiting this decision.

Regarding data structure modifications, you're totally right that this is nontrivial. We will need some way to handle migrations (in either case). I haven't thought much about how we might do this yet. One thought is just to have scripts that could migrate pickle files from, say, `v2.0.0` to `v2.1.0`.

**Comment by jonorthwash** [comment]
I think in general, the approach of rewriting the file (whether json or pickle) every time a crosshair is modified isn't the best idea.  Perhaps the model should be something like save on updates, except no more often than every 30 seconds (or however much).

**Comment by jonorthwash** [comment]
Also, I don't mind having metadata and traces stored separately, but do note that scripts that do analysis will need to read both (and also the TextGrids).

**Comment by keggsmurph21** [comment]
I think one way to handle minimizing extraneous saves is to hook into
Python’s signal library, which would allow us to run a function on program
exit. Then we could have something like

import signal
from .app import app  # global singleton ref
def on_exit_hook(*args):
    app.save()

signal.signal(signal.EXIT, on_exit_hook)  # don't recall exact API

**Comment by jonorthwash** [comment]
> I think one way to handle minimizing extraneous saves is to hook into Python’s signal library, which would allow us to run a function on program exit.

What I worry about here is in issues of program instability (crashes), random power outage, etc., we would lose a lot of work.  I much prefer periodically saving the data.

**Comment by kmurphy4** [comment]
So theoretically, this would protect against crashes but not system
outages. Periodic saves would be a good compromise. If we're worried about
performance, we could try to figure out some sort of background process
solution, but that seems unlikely.

This could also be a parameter that the user sets, e.g.
`--autosave-interval 30`.

**Comment by jonorthwash** [comment]
I don't need it to save every 30 seconds; it's more that it'd be better to wait 30 seconds between saves than to keep saving repeatedly if data is being updated multiple times a second.  I think the general approach of saving when data is updated is better than periodic saves or save-on-close—the only problem with this approach is hitting the disk so often, which is what the short wait I propose is supposed to mitigate.

**Comment by kmurphy4** [comment]
Sorry, I meant 30 seconds as a max.  So yes, I agree with you.

**Comment by jonorthwash** [comment]
> this would protect against crashes

I don't understand this part either, btw.  The are enough moving parts that could fail that anything could crash.  I don't see how saving at the end protects against this, or protects data from being lost if a crash were to happen.

**Comment by keggsmurph21** [comment]
> > this would protect against crashes
> 
> I don't understand this part either, btw. The are enough moving parts that could fail that anything could crash. I don't see how saving at the end protects against this, or protects data from being lost if a crash were to happen.

Here's a proof-of-concept (I realized that the library I was thinking of is actually called `atexit`) -- running this file:
```python
import atexit

def on_exit_hook(*args):
    print('in hook!')

atexit.register(on_exit_hook)

raise RuntimeError('test')
print('after test')
```
gives this result:
```bash
$ python crash-test.py 
Traceback (most recent call last):
  File "crash-test.py", line 8, in <module>
    raise RuntimeError('test')
RuntimeError: test
in hook!
```

That means that as long as we don't crash _in the function body of `App::save`_, then we should be able to just register this hook and rely on it being called even if we crash for unknown reasons (besides segfaults, which are pretty rare).

**Comment by keggsmurph21** [comment]
[The docs](https://docs.python.org/3/library/atexit.html#atexit-example) have a more extended example if you're curious.

**Comment by jonorthwash** [comment]
I think this issue has been addressed, and new issues can be opened for anything related.
